global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Node.js backend metrics
  - job_name: 'perlme-backend'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['127.0.0.1:3000']  # your backend on VPS
    honor_labels: true
    # Add the internal token header
    authorization:
      type: "Bearer"
      credentials: "OWI0LTIxNmIyYTM1NDQ4YSIsImVtYWlsIjoiZ2FrZW55ZWRlc2lnbnNAZ21haWwuY29tIiwicm9sZSI6IlJFR1VMQVIiLCJ1c2VybmFtZSI6IlVzZXJHYWtlbnllIiwiaWF0IjoxNzYxMzk4MjYzLCJleHAiOjE3NjE0MDE4NjN9.wuTH6bBLGYHKYdrIGcU_v7Wr_vbzeXUfNkY4wNDmMck"
